site_name: Turkish Super League Toolkit
site_description: FastAPI & Dataset Exporter for the Trendyol Super League
repo_url: https://github.com/kaany43/Turkish-Super-League-toolkit
repo_name: kaany43/Turkish-Super-League-toolkit

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.copy

nav:
  - Home: index.md
  - Installation: installation.md
  - REST API Reference: api_reference.md
  - Dataset Exporter: dataset_exporter.md