"""
Sofascore İngilizce ülke adı -> Türkçe gösterim
"""

# Eksik anahtarlar için İngilizce etiket gösterilir
COUNTRY_EN_TO_TR: dict[str, str] = {
    "Turkey": "Türkiye",
    "Türkiye": "Türkiye",
    "Brazil": "Brezilya",
    "Germany": "Almanya",
    "France": "Fransa",
    "Netherlands": "Hollanda",
    "Portugal": "Portekiz",
    "Spain": "İspanya",
    "Italy": "İtalya",
    "England": "İngiltere",
    "Scotland": "İskoçya",
    "Wales": "Galler",
    "Northern Ireland": "Kuzey İrlanda",
    "Belgium": "Belçika",
    "Croatia": "Hırvatistan",
    "Serbia": "Sırbistan",
    "Bosnia & Herzegovina": "Bosna-Hersek",
    "Montenegro": "Karadağ",
    "Slovenia": "Slovenya",
    "Slovakia": "Slovakya",
    "Czechia": "Çekya",
    "Czech Republic": "Çekya",
    "Poland": "Polonya",
    "Ukraine": "Ukrayna",
    "Romania": "Romanya",
    "Bulgaria": "Bulgaristan",
    "Greece": "Yunanistan",
    "Cyprus": "Kıbrıs",
    "Albania": "Arnavutluk",
    "North Macedonia": "Kuzey Makedonya",
    "Kosovo": "Kosova",
    "Hungary": "Macaristan",
    "Austria": "Avusturya",
    "Switzerland": "İsviçre",
    "Sweden": "İsveç",
    "Norway": "Norveç",
    "Denmark": "Danimarka",
    "Finland": "Finlandiya",
    "Iceland": "İzlanda",
    "Ireland": "İrlanda",
    "Russia": "Rusya",
    "Belarus": "Belarus",
    "Moldova": "Moldova",
    "Georgia": "Gürcistan",
    "Armenia": "Ermenistan",
    "Azerbaijan": "Azerbaycan",
    "Kazakhstan": "Kazakistan",
    "Israel": "İsrail",
    "Palestine": "Filistin",
    "Jordan": "Ürdün",
    "Lebanon": "Lübnan",
    "Syria": "Suriye",
    "Iraq": "Irak",
    "Iran": "İran",
    "Saudi Arabia": "Suudi Arabistan",
    "United Arab Emirates": "BAE",
    "Qatar": "Katar",
    "Kuwait": "Kuveyt",
    "Oman": "Umman",
    "Bahrain": "Bahreyn",
    "Yemen": "Yemen",
    "Egypt": "Mısır",
    "Morocco": "Fas",
    "Algeria": "Cezayir",
    "Tunisia": "Tunus",
    "Libya": "Libya",
    "Sudan": "Sudan",
    "South Africa": "Güney Afrika",
    "Senegal": "Senegal",
    "Nigeria": "Nijerya",
    "Ghana": "Gana",
    "Cameroon": "Kamerun",
    "Ivory Coast": "Fildişi Sahili",
    "Mali": "Mali",
    "Burkina Faso": "Burkina Faso",
    "Guinea": "Gine",
    "Togo": "Togo",
    "Benin": "Benin",
    "Gabon": "Gabon",
    "Congo DR": "Kongo DC",
    "Congo": "Kongo",
    "Angola": "Angola",
    "Zambia": "Zambiya",
    "Zimbabwe": "Zimbabve",
    "Kenya": "Kenya",
    "Uganda": "Uganda",
    "Tanzania": "Tanzanya",
    "Rwanda": "Ruanda",
    "Burundi": "Burundi",
    "Ethiopia": "Etiyopya",
    "Eritrea": "Eritre",
    "Somalia": "Somali",
    "Djibouti": "Cibuti",
    "Mauritania": "Moritanya",
    "Cape Verde": "Yeşil Burun Adaları",
    "Gambia": "Gambiya",
    "Guinea-Bissau": "Gine-Bissau",
    "Equatorial Guinea": "Ekvator Ginesi",
    "Central African Republic": "Orta Afrika Cumhuriyeti",
    "Chad": "Çad",
    "Niger": "Nijer",
    "Namibia": "Namibya",
    "Botswana": "Botsvana",
    "Mozambique": "Mozambik",
    "Madagascar": "Madagaskar",
    "Mauritius": "Mauritius",
    "Seychelles": "Seyşeller",
    "Comoros": "Komorlar",
    "Lesotho": "Lesotho",
    "Eswatini": "Esvatini",
    "South Sudan": "Güney Sudan",
    "Argentina": "Arjantin",
    "Uruguay": "Uruguay",
    "Paraguay": "Paraguay",
    "Chile": "Şili",
    "Colombia": "Kolombiya",
    "Venezuela": "Venezuela",
    "Ecuador": "Ekvador",
    "Peru": "Peru",
    "Bolivia": "Bolivya",
    "Guyana": "Guyana",
    "Suriname": "Surinam",
    "Panama": "Panama",
    "Costa Rica": "Kosta Rika",
    "Nicaragua": "Nikaragua",
    "Honduras": "Honduras",
    "El Salvador": "El Salvador",
    "Guatemala": "Guatemala",
    "Belize": "Belize",
    "Mexico": "Meksika",
    "United States": "ABD",
    "Canada": "Kanada",
    "Jamaica": "Jamaika",
    "Trinidad and Tobago": "Trinidad ve Tobago",
    "Haiti": "Haiti",
    "Dominican Republic": "Dominik Cumhuriyeti",
    "Cuba": "Küba",
    "Puerto Rico": "Porto Riko",
    "Australia": "Avustralya",
    "New Zealand": "Yeni Zelanda",
    "Japan": "Japonya",
    "South Korea": "Güney Kore",
    "North Korea": "Kuzey Kore",
    "China": "Çin",
    "Hong Kong": "Hong Kong",
    "Taiwan": "Tayvan",
    "India": "Hindistan",
    "Pakistan": "Pakistan",
    "Bangladesh": "Bangladeş",
    "Sri Lanka": "Sri Lanka",
    "Nepal": "Nepal",
    "Bhutan": "Butan",
    "Afghanistan": "Afganistan",
    "Uzbekistan": "Özbekistan",
    "Kyrgyzstan": "Kırgızistan",
    "Tajikistan": "Tacikistan",
    "Turkmenistan": "Türkmenistan",
    "Mongolia": "Moğolistan",
    "Thailand": "Tayland",
    "Vietnam": "Vietnam",
    "Laos": "Laos",
    "Cambodia": "Kamboçya",
    "Myanmar": "Myanmar",
    "Malaysia": "Malezya",
    "Singapore": "Singapur",
    "Indonesia": "Endonezya",
    "Philippines": "Filipinler",
    "Brunei": "Brunei",
    "East Timor": "Doğu Timor",
    "Papua New Guinea": "Papua Yeni Gine",
    "Fiji": "Fiji",
    "New Caledonia": "Yeni Kaledonya",
    "Tahiti": "Tahiti",
    "Luxembourg": "Lüksemburg",
    "Liechtenstein": "Liechtenstein",
    "Malta": "Malta",
    "Andorra": "Andorra",
    "San Marino": "San Marino",
    "Monaco": "Monako",
    "Vatican": "Vatikan",
    "Gibraltar": "Cebelitarık",
    "Faroe Islands": "Faroe Adaları",
    "Estonia": "Estonya",
    "Latvia": "Letonya",
    "Lithuania": "Litvanya",
    "Curacao": "Curaçao",
    "Aruba": "Aruba",
    "Bermuda": "Bermuda",
    "Puerto Rico": "Porto Riko",
    "Martinique": "Martinik",
    "Guadeloupe": "Guadeloupe",
    "French Guiana": "Fransız Guyanası",
    "Réunion": "Réunion",
    "Mayotte": "Mayotte",
    "Zanzibar": "Zanzibar",
    "Curaçao": "Curaçao",
}


def country_label_turkish(english_key: str) -> str:
    k = (english_key or "").strip()
    if not k:
        return "Bilinmiyor"
    return COUNTRY_EN_TO_TR.get(k, k)
